sudo: required
dist: trusty
language: node
env:
  - GIMME_OS=linux GIMME_ARCH=amd64 PATH=$TRAVIS_BUILD_DIR/linux_amd64:$PATH
go:
  - 1.10
node_js:
  - 8
before_install:
  # Install the arm32 cross-compiler
  - sudo apt-add-repository 'deb http://archive.ubuntu.com/ubuntu artful main'
  - sudo apt-get update -qq
  # Correct rake bug
  - RAKE=`which rake`
  - mv `which rake` `which rake`.old
  - touch ${RAKE}
  - chmod 755 ${RAKE}
install:
  - which node
  - which npm
deploy:
  provider: releases
  overwrite: true
  api_key: "$GITHUB_OAUTH2_KEY"
  file:
  - "${TRAVIS_BUILD_DIR}/mqtt-webhook.js"
  - "${TRAVIS_BUILD_DIR}/mqtt-webhook-service"
  - "${TRAVIS_BUILD_DIR}/package.json"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
after_deploy: echo "deploiement terminé"